spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true
    username: root
    password: Cpp&Java@cool2000S
## Specify DBMS
  jpa:
    show-sql: false
# Hibernate DDL Auto (Create , Create-drop , update)
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081
  error:
    include-message: on_param


